#!/bin/sh

./Release/AutoTester AutoTester/Test-Cases/sources/testcase1-source.txt AutoTester/Test-Cases/queries/testcase1-queries.txt AutoTester/Test-Cases/output/testcase1-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/testcase2-source.txt AutoTester/Test-Cases/queries/testcase2-queries.txt AutoTester/Test-Cases/output/testcase2-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/testcase3-source.txt AutoTester/Test-Cases/queries/testcase3-queries.txt AutoTester/Test-Cases/output/testcase3-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/testcase4-source.txt AutoTester/Test-Cases/queries/testcase4-queries.txt AutoTester/Test-Cases/output/testcase4-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/testcase5-source.txt AutoTester/Test-Cases/queries/testcase5-queries.txt AutoTester/Test-Cases/output/testcase5-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/testcase6-source.txt AutoTester/Test-Cases/queries/testcase6-queries.txt AutoTester/Test-Cases/output/testcase6-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/testcase7-source.txt AutoTester/Test-Cases/queries/testcase7-queries.txt AutoTester/Test-Cases/output/testcase7-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/testcase8-source.txt AutoTester/Test-Cases/queries/testcase8-queries.txt AutoTester/Test-Cases/output/testcase8-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/testcase9-source.txt AutoTester/Test-Cases/queries/testcase9-queries.txt AutoTester/Test-Cases/output/testcase9-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/testcase10-source.txt AutoTester/Test-Cases/queries/testcase10-queries.txt AutoTester/Test-Cases/output/testcase10-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/testcase11-source.txt AutoTester/Test-Cases/queries/testcase11-queries.txt AutoTester/Test-Cases/output/testcase11-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/testcase12-source.txt AutoTester/Test-Cases/queries/testcase12-queries.txt AutoTester/Test-Cases/output/testcase12-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/testcase13-source.txt AutoTester/Test-Cases/queries/testcase13-queries.txt AutoTester/Test-Cases/output/testcase13-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/testcase14-source.txt AutoTester/Test-Cases/queries/testcase14-queries.txt AutoTester/Test-Cases/output/testcase14-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/testcase15-source.txt AutoTester/Test-Cases/queries/testcase15-queries.txt AutoTester/Test-Cases/output/testcase15-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/testcase16-source.txt AutoTester/Test-Cases/queries/testcase16-queries.txt AutoTester/Test-Cases/output/testcase16-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/testcase17-source.txt AutoTester/Test-Cases/queries/testcase17-queries.txt AutoTester/Test-Cases/output/testcase17-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/testcase18-source.txt AutoTester/Test-Cases/queries/testcase18-queries.txt AutoTester/Test-Cases/output/testcase18-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/testcase19-source.txt AutoTester/Test-Cases/queries/testcase19-queries.txt AutoTester/Test-Cases/output/testcase19-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/testcase20-source.txt AutoTester/Test-Cases/queries/testcase20-queries.txt AutoTester/Test-Cases/output/testcase20-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/testcase21-source.txt AutoTester/Test-Cases/queries/testcase21-queries.txt AutoTester/Test-Cases/output/testcase21-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/testcase22-source.txt AutoTester/Test-Cases/queries/testcase22-queries.txt AutoTester/Test-Cases/output/testcase22-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/testcase23-source.txt AutoTester/Test-Cases/queries/testcase23-queries.txt AutoTester/Test-Cases/output/testcase23-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/blackbox1-source.txt AutoTester/Test-Cases/queries/blackbox1-queries.txt AutoTester/Test-Cases/output/blackbox1-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/blackbox2-source.txt AutoTester/Test-Cases/queries/blackbox2-queries.txt AutoTester/Test-Cases/output/blackbox2-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/extension1-source.txt AutoTester/Test-Cases/queries/extension1-queries.txt AutoTester/Test-Cases/output/extension1-out.xml
./Release/AutoTester AutoTester/Test-Cases/sources/extension2-source.txt AutoTester/Test-Cases/queries/extension2-queries.txt AutoTester/Test-Cases/output/extension2-out.xml
